COLUMNS = 7
ROWS = 6
DEFAULT_MARK = "-"

UI_SCALING = 2.5
CHOICE_HISTORY_MAX = 43
BUTTON_START = "Start Round"
BUTTON_EXIT = "Exit Game"
BUTTON_UNDO = "Undo Move"
BUTTON_ABORT = "Abort Round"
POPUP_TIE = "Tie Game!"
